services:
  - type: web
    name: dodgebucks
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    branch: main
    envVars:
      - key: WALLET
        value: 0x373c989C2721963264932BF266605C8c7f503f65
      - key: TOKEN_API
        value: Iuwv6Zb1dGVAoEOR-W4Z1h34T691GQiZ
