services:
  - type: web
    name: dodgebucks-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: WALLET_ADDRESS
        fromSecret: WALLET_ADDRESS
      - key: TOKEN_API
        fromSecret: TOKEN_API
