services:
  - type: web
    name: dodgebucks-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: WALLET_ADDRESS
        sync: true
      - key: TOKEN_API
        sync: true

  - type: static
    name: dodgebucks-frontend
    env: static
    plan: free
    staticPublishPath: frontend
    autoDeploy: true
